### ISSUE TITLE
The test type is mostly 'automated', but some test...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#11]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

The test type is mostly 'automated', but some test are 'manual' or it is unclear. However, in some cases a requirement is considered 'not testable' where a manual test might be possible.
It is clear that the ETS will only implement automated tests, but it may be helpful to understand if manual tests are within the scope of the ATSs or not.
# Proposed Change

Clarify.

**Comment by michellutz** [comment]
This issue was discussed in the [MIWP-5 web-conference on 16 March](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_8#Scope-of-the-ATSs-automated-vs-manual-vs-not-testable). The conclusions were:
- Manual tests should be included in the ATSs
- Manual tests could be a "skipped" test in the ETS test report... with some additional instructions. on how to conduct the test manually

The distinction between manual vs. not testable was not discussed at the meeting. 

I would propose to 
- not use "not testable" as a test type
- where manual testing is possible, change the test type to "manual" 
- where a requirement cannot even be tested manually, remove or reword the requirement

**Comment by cportele** [comment]
I agree with the proposal regarding "not testable"
