### ISSUE TITLE
Links point to the github repository....

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#12]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Links point to the github repository.
# Proposed Change

Make them relative links (into the document)

**Comment by cportele** [comment]
Not understood. Relative links would always point to GitHub as the origin is in GitHub.

But it is an open question what URIs should be used in the future. This is related to the management and maintenance. Will the GitHub pages continue to be the authoritative source for the INSPIRE ATSs? If GitHub is continue to be used, should links point to GitHub or should more neutral URIs be used - with redirections to the GitHub URIs?

**Comment by ilkkarinne** [comment]
I would suggest using neutral, stable URIs (under http://inspire.ec.europa.eu/) + redirection to the current official locations. This way we have a method of not breaking the links when relocating the ATSes.

**Comment by cportele** [comment]
I am reassigning this to JRC as they are the owners of http://inspire.ec.europa.eu/ and eventually will have to make the decision and implement it.

**Comment by michellutz** [comment]
In general, I agree with the proposal to define URIs in the  http://inspire.ec.europa.eu/ namespace to refer to conformance classes. I am not so sure about individual tests, but if we see a need for this, this could be done as well.

We would need to define the requirements we have for these URIs. Then I can have a discussion with the INSPIRE registry team to see whether/how this can be implemented (and by when).

So I would propose to accept the proposal with modifications. But further work is still needed.

Maybe we can shortly discuss the way forward in the 2nd comment resolution web-conference.

**Comment by michellutz** [comment]
Resolution from [Comment resolution workshop](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10):
- Agreed to define persistent URIs for the ATSs in the http://inspire.ec.europa.eu namespace to refer to conformance classes and also test cases, in order to guarantee persistence (if ATSs are moved from GitHub)
- Redirect to the current implementation (pure redirect, no additional metadata)
- Also for INSPIRE Test Cases to be able to link from ETSs
- Potential pattern: http://inspire.ec.europa.eu/ats/<tg-id>/<version>/<cc-id>/<test-case-id>

**[Action]** JRC to specify URI pattern and to implement redirects once the CCs are stable.
